<?php 
/*


*/
include('admin/dbconnect.php');
include('smarty_init.php');	

	//从数据库中取出相关信息
	$dbconnect=new DBconnect();
	$conn=$dbconnect->open();
	//显示
	$sql="select * from lzu_st_news order by id desc";
	$res=mysql_query($sql,$conn);
	$i=1;
	if(mysql_num_rows($res)>0){
		while($row=mysql_fetch_array($res)){
			if($row['rid']==0)
			{
			   $t0[$i]['title']=$row['title'];
			   $t0[$i]['time']=$row['time'];
			   $t0[$i]['id']=$row['id'];
			   $i++;
			   continue;
			}
			if($row['rid']==1)
			{
			   $t1[$i]['title']=$row['title'];
			   $t1[$i]['time']=$row['time'];
			   $t1[$i]['id']=$row['id'];
			   $i++;
			   continue;
			}			
			if($row['rid']==2)
			{
			   $t2[$i]['title']=$row['title'];
			   $t2[$i]['time']=$row['time'];
			   $t2[$i]['id']=$row['id'];
			   $i++;
			   continue;
			}
			if($row['rid']==3)
			{
			   $t3[$i]['title']=$row['title'];
			   $t3[$i]['time']=$row['time'];
			   $t3[$i]['id']=$row['id'];
			   $t3[$i]['image']=$row['image'];
			   $i++;
			   continue;
			}
			if($row['rid']==4)
			{
			   $t4[$i]['title']=$row['title'];
			   $t4[$i]['time']=$row['time'];
			   $t4[$i]['id']=$row['id'];
			   $i++;
			   continue;
			}
		}
	}
	$sqltype="select * from lzu_st_type";
	$restype=mysql_query($sqltype,$conn);
	if(mysql_num_rows($restype)>0){
	while($rowtype=mysql_fetch_array($restype)){
	if($rowtype['rid']==0)$titletype0['type']=$rowtype['type'];
	if($rowtype['rid']==1)$titletype1['type']=$rowtype['type'];
	if($rowtype['rid']==2)$titletype2['type']=$rowtype['type'];
	if($rowtype['rid']==3)$titletype3['type']=$rowtype['type'];
	if($rowtype['rid']==4)$titletype4['type']=$rowtype['type'];
	}
	}
    $smarty->assign('t0',$t0);
	$smarty->assign('t1',$t1);
	$smarty->assign('t2',$t2);
	$smarty->assign('t3',$t3);
	$smarty->assign('t4',$t4);
	$smarty->assign('titletype0',$titletype0['type']);
	$smarty->assign('titletype1',$titletype1['type']);
	$smarty->assign('titletype2',$titletype2['type']);
	$smarty->assign('titletype3',$titletype3['type']);
	$smarty->assign('titletype4',$titletype4['type']);
	$smarty->display('index.html');
?>

